doctrine:
    dbal:
        dbname: '%env(resolve:DATABASE_NAME)%'
        user: '%env(resolve:DATABASE_USER)%'
        password: '%env(resolve:DATABASE_PASSWORD)%'
        host: '%env(resolve:DATABASE_HOST)%'
        port: '%env(resolve:DATABASE_PORT)%'
        driver: '%env(resolve:DATABASE_DRIVER)%'
        server_version: '%env(resolve:DATABASE_VERSION)%'
    orm:
        auto_generate_proxy_classes: true
        enable_lazy_ghost_objects: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            TaskManagerProjects:
                type: xml
                dir: '%kernel.project_dir%/../src/Projects/Infrastructure/Persistence/Doctrine'
                is_bundle: false
                prefix: TaskManager\Projects\Domain\Entity
                alias: TaskManagerProjects
            TaskManagerUsers:
                type: xml
                dir: '%kernel.project_dir%/../src/Users/Infrastructure/Persistence/Doctrine'
                is_bundle: false
                prefix: TaskManager\Users\Domain\Entity
                alias: TaskManagerUsers

when@test:
    doctrine:
        dbal:
            # "TEST_TOKEN" is typically set by ParaTest
            dbname_suffix: '_test%env(default::TEST_TOKEN)%'

when@prod:
    doctrine:
        orm:
            auto_generate_proxy_classes: false
            proxy_dir: '%kernel.build_dir%/doctrine/orm/Proxies'
            query_cache_driver:
                type: pool
                pool: doctrine.system_cache_pool
            result_cache_driver:
                type: pool
                pool: doctrine.result_cache_pool

    framework:
        cache:
            pools:
                doctrine.result_cache_pool:
                    adapter: cache.app
                doctrine.system_cache_pool:
                    adapter: cache.system
