doctrine:
    dbal:
        dbname: '%env(resolve:DATABASE_NAME)%'
        user: '%env(resolve:DATABASE_USER)%'
        password: '%env(resolve:DATABASE_PASSWORD)%'
        host: '%env(resolve:DATABASE_HOST)%'
        port: '%env(resolve:DATABASE_PORT)%'
        driver: '%env(resolve:DATABASE_DRIVER)%'
        server_version: '%env(resolve:DATABASE_VERSION)%'
        types:
            user_id: TaskManager\Users\Infrastructure\Persistence\Doctrine\UserIdType
            user_email: TaskManager\Users\Infrastructure\Persistence\Doctrine\UserEmailType
            user_firstname: TaskManager\Users\Infrastructure\Persistence\Doctrine\UserFirstnameType
            user_lastname: TaskManager\Users\Infrastructure\Persistence\Doctrine\UserLastnameType
            user_password: TaskManager\Users\Infrastructure\Persistence\Doctrine\UserPasswordType

            project_user_id: TaskManager\Projects\Infrastructure\Persistence\Doctrine\ProjectUserIdType
            project_id: TaskManager\Projects\Infrastructure\Persistence\Doctrine\ProjectIdType
            project_name: TaskManager\Projects\Infrastructure\Persistence\Doctrine\ProjectNameType
            project_description: TaskManager\Projects\Infrastructure\Persistence\Doctrine\ProjectDescriptionType
            project_finish_date: TaskManager\Projects\Infrastructure\Persistence\Doctrine\ProjectFinishDateType
            project_status: TaskManager\Projects\Infrastructure\Persistence\Doctrine\ProjectStatusType
    orm:
        auto_generate_proxy_classes: true
        enable_lazy_ghost_objects: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            TaskManagerProjects:
                type: xml
                dir: '%kernel.project_dir%/../src/Projects/Infrastructure/Persistence/Doctrine'
                is_bundle: false
                prefix: TaskManager\Projects\Domain
                alias: TaskManagerProjects
            TaskManagerUsers:
                type: xml
                dir: '%kernel.project_dir%/../src/Users/Infrastructure/Persistence/Doctrine'
                is_bundle: false
                prefix: TaskManager\Users\Domain
                alias: TaskManagerUsers

when@test:
    doctrine:
        dbal:
            # "TEST_TOKEN" is typically set by ParaTest
            dbname_suffix: '_test%env(default::TEST_TOKEN)%'

when@prod:
    doctrine:
        orm:
            auto_generate_proxy_classes: false
            proxy_dir: '%kernel.build_dir%/doctrine/orm/Proxies'
            query_cache_driver:
                type: pool
                pool: doctrine.system_cache_pool
            result_cache_driver:
                type: pool
                pool: doctrine.result_cache_pool

    framework:
        cache:
            pools:
                doctrine.result_cache_pool:
                    adapter: cache.app
                doctrine.system_cache_pool:
                    adapter: cache.system
